/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Color;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sandun Jayasooriya
 */
public class AlarmForm extends javax.swing.JFrame {
    
    private AudioClip audioClip;
    
    /**
     * Creates new form Alarm
     */
    public AlarmForm() {
        initComponents();
        setLocation(1000,200);
        URL url = getClass().getResource("/audio/tone.wav");
        audioClip = Applet.newAudioClip(url);
        btnAlarm.setBackground(Color.GREEN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAlarm = new javax.swing.JLabel();
        btnAlarm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(291, 227));
        getContentPane().setLayout(null);

        btnAlarm.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        btnAlarm.setText("Off");
        btnAlarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlarmActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlarm);
        btnAlarm.setBounds(60, 70, 158, 66);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlarmActionPerformed
       audioClip.stop();
    }//GEN-LAST:event_btnAlarmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlarmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlarmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlarmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlarmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlarmForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlarm;
    private javax.swing.JLabel lblAlarm;
    // End of variables declaration//GEN-END:variables

   
    
    public void setWaterTankLevel(int level) {
        try {
            if (level > 50) {
                audioClip.play();
                btnAlarm.setBackground(Color.red);
                btnAlarm.setText("On");
            } else {
                audioClip.stop();
                btnAlarm.setBackground(Color.GREEN);
                btnAlarm.setText("Off");
            }
        } catch (Exception ex) {
            Logger.getLogger(AlarmForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
